### PR TITLE
fixed drag&drop

### LINKED ISSUE #944: Drag and Drop not working
I'm using dnspy v5.0.7 and I'm having a problem while trying to drop a .NET assembly or exe in Assembly Explorer. I can just use File > Open but for me Drag and drop is a faster way and it doesn't work for me when I try to drop a file in the assembly explorer.

### PR DESCRIPTION
**Pull request by LFriede**
Should fix #944

### CODE REVIEW

File: dnSpy/dnSpy/Documents/TreeView/DocumentTreeView.cs [hunk 1]
```diff
@@ -753,16 +753,11 @@ sealed class AddDocumentInfo {
...
-				var file = Path.GetFileName(filenames[i]);
-
-				var shell = new Shell32.Shell();
-				var folder = shell.NameSpace(directory);
-				var folderItem = folder.ParseName(file);
-				if (folderItem != null && folderItem.IsLink) {
-					var link = (Shell32.ShellLinkObject)folderItem.GetLink;
-					filenames[i] = link.Path;
-				}
+				var ws = new IWshRuntimeLibrary.WshShell();
```
Comment (0xd4d) [inline dnSpy/dnSpy/Documents/TreeView/DocumentTreeView.cs]: This one could also be placed inside the try block.

Since exceptions are slow and a user can drag many files, you should set a boolean to false if an exception is thrown and not execute this code again.

Comment (0xd4d) [reply dnSpy/dnSpy/Documents/TreeView/DocumentTreeView.cs]: It can be a local initialized before the loop.

**Comment by 0xd4d** [comment]
Thanks for the fix!

**Comment by LFriede** [comment]
Since I broke it I'm happy to solve it =)
